language: python
python:
   - "3.5"
   - "3.3"
   - "2.7"

# install dependencies
virtualenv:
    system_site_packages: true
env:
  - DJANGO_VERSION=2.0.7
  - DJANGO_SETTINGS_MODULE='scr.settings'

install:
  - pip install -r requirements.txt

script: python manage.py test

