language: python
python:
   - "3.5"
   - "3.3"
   - "2.7"

# install dependencies
virtualenv:
    system_site_packages: true


install:
  - pip install -r requirements.txt

script: python manage.py test

