language: python
python:
   - "3.5"
   - "3.3"
   - "2.7"

env:
  - DJANGO_VERSION=2.0.7
  - DJANGO_SETTINGS_MODULE='scr.settings'

install:
  - find . -regex '.*requirements.txt$'
  - pip install -r requirements.txt

script: python manage.py test

