apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8000

---                           

apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 80
      targetPort: 8000
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server        
          image: nkirui2030/matatusawa:v1
          ports:
            - containerPort: 8000
      

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'nathankirui5@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: smaldynamics-ml-tls
spec:
  secretName: smaldynamics-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: smaldynamics.ml
  dnsNames:
    - smaldynamics.ml
    - www.smaldynamics.ml
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - smaldynamics.ml
          - www.smaldynamics.ml