# File structure version
version: '2'

services:
  # Our django application
  # Build from remote dockerfile
  # Connect local app folder with image folder, so changes will be pushed to image instantly
  # Open port 8000
  nginx:
    image: nginx
    volumes:
    - ./configurations/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    
    depends_on:
      - main_app
    ports:
      - "80:80" 
      - "443:443" 
    command: [nginx-debug, '-g', 'daemon off;']
    restart: always

  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: main_app
    volumes:
      - ./main_app:/main_app  
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=kitumbaya
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - django-db-data:/var/lib/postgresql/data/pgdata
    restart: always


volumes:
  django-db-data: