# Generated by Django 2.0.7 on 2018-07-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msacco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='fnames',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='snames',
            new_name='sname',
        ),
    ]
