# Generated by Django 2.0.7 on 2018-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msacco', '0002_auto_20180706_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='employer',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='fname',
            field=models.CharField(default='', max_length=250, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='sname',
            field=models.CharField(default='', max_length=250, verbose_name='Second Name'),
        ),
    ]
