# Generated by Django 2.0.7 on 2018-09-02 22:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_saccodriver', models.BooleanField(default=True, verbose_name='Driver status')),
                ('is_saccoowner', models.BooleanField(default=True, verbose_name='Owner status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users Account',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=30, verbose_name='First Name')),
                ('l_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('dl', models.CharField(default='', max_length=100, verbose_name='Driving Licence')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('route', models.CharField(default='', max_length=100)),
                ('image', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='media', verbose_name='Profile Picture')),
                ('emp_rmks', models.TextField(default='', max_length=100, verbose_name='Employer Remarks')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': ' Sacco Driver Details',
            },
        ),
        migrations.CreateModel(
            name='Saccoowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=100, verbose_name='National Id or Passport')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Tel')),
                ('address', models.CharField(help_text='P.O Box 357', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sacco Owner')),
            ],
            options={
                'verbose_name_plural': 'The Owners Of The Sacco',
            },
        ),
        migrations.CreateModel(
            name='SaccoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_name', models.CharField(max_length=100, unique=True, verbose_name='Sacco Name')),
                ('sacco_address', models.CharField(help_text='P.O Box 357', max_length=200)),
                ('sacco_phonenumber', models.CharField(max_length=12, verbose_name='Tel')),
                ('sacco_url', models.CharField(default='', max_length=250, verbose_name='Website')),
                ('town', models.CharField(blank=True, choices=[('None', 'None'), ('Kasarani', 'Kasarani'), ('Kawangware', 'Kawangware'), ('Uthiru', 'Uthiru'), ('Pipeline', 'Pipeline'), ('Ngong', 'Ngong'), ('Dohnholm', 'Dohnholm'), ('Kilimani', 'Kilimani')], default=0, max_length=10, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='msacco.Saccoowner')),
            ],
            options={
                'verbose_name_plural': 'Sacco profile Details',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('B', '--------'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('picture', models.FileField(blank=True, upload_to='media')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('employer', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffprofiles', to='msacco.SaccoProfile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name_plural': 'Sacco Staff Profiles',
            },
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='msacco.SaccoProfile'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driverprofiles', to='msacco.Saccoowner', verbose_name='Driver'),
        ),
    ]
