# Generated by Django 2.0.7 on 2018-09-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_status',
            field=models.CharField(choices=[('E', 'Employed'), ('D', 'Dismissed'), ('R', 'Resigned'), ('L', 'Left')], default='', max_length=1),
        ),
    ]
