# Generated by Django 2.0.7 on 2018-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msacco', '0003_auto_20180911_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Dismissed', 'Dismissed'), ('Resigned', 'Resigned'), ('Left', 'Left')], default='', max_length=100),
        ),
    ]
