# Generated by Django 2.0.7 on 2018-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msacco', '0008_auto_20180912_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='emp_rmks',
            field=models.CharField(choices=[('AVARAGE DRIVER', 'Avarage driver'), ('GOOD DRIVER', 'Good driver'), ('VERY GOOD', 'Very Good'), ('WORST DRIVER', 'Worst driver')], default='Good driver', max_length=100, verbose_name='Employer Remarks'),
        ),
    ]
